apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-topics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-topics
  template:
    metadata:
      labels:
        app: kafka-topics
    spec:
      containers:
        - name: kafka-topics
          image: confluentinc/cp-kafka:5.5.0
          command:
            [
              "bash",
              "-c",
              "echo creating topics && kafka-topics --bootstrap-server kafka-1:9092 --create --topic X --partitions 1 --replication-factor 3",
            ]
          volumeMounts:
            - name: kafka-topic-data
              mountPath: /var/lib/kafka/data
            - name: kafka-secrets
              mountPath: /etc/kafka/secrets
          env:
            - name: KAFKA_BROKERCONNECT
              value: "kafka-1:9092"
      volumes:
        - name: kafka-topic-data
          persistentVolumeClaim:
            claimName: kafka-topic-data
        - name: kafka-secrets
          persistentVolumeClaim:
            claimName: kafka-data
