apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: consumer1
  name: consumer1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consumer1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/opt-default: "true"
        io.kompose.service: consumer1
    spec:
      containers:
        - env:
            - name: CONSUMER_ID
              value: "1"
            - name: KAFKA_BROKERCONNECT
              value: kafka-1:9092
            - name: TOPIC
              value: X
          image: consumer1
          name: consumer1
          resources: {}
          volumeMounts:
            - mountPath: /kafkarun.py
              name: consumer1-claim0
      restartPolicy: Always
      volumes:
        - name: consumer1-claim0
          persistentVolumeClaim:
            claimName: consumer1-claim0
status: {}
