apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: kafdrop
  name: kafdrop
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafdrop
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/opt-default: "true"
        io.kompose.service: kafdrop
    spec:
      containers:
        - env:
            - name: KAFKA_BROKERCONNECT
              value: kafka-1:9092
            - name: SERVER_SERVLET_CONTEXTPATH
              value: /
          image: obsidiandynamics/kafdrop:latest
          name: kafdrop
          ports:
            - containerPort: 9000
          resources: {}
      restartPolicy: Always
status: {}
