apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-1
  name: kafka-1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/opt-default: "true"
        io.kompose.service: kafka-1
    spec:
      containers:
        - env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-1:9092
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
          image: confluentinc/cp-kafka:5.5.0
          livenessProbe:
            exec:
              command:
                - /usr/bin/kafka-topics --list --zookeeper zookeeper:2181
          name: kafka-1
          ports:
            - containerPort: 9092
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/kafka/data
              name: kafka-data1
            - mountPath: /etc/kafka/secrets
              name: kafka-data1
      restartPolicy: Always
      volumes:
        - name: kafka-data1
          persistentVolumeClaim:
            claimName: kafka-data1
        - name: kafka-data1
          persistentVolumeClaim:
            claimName: kafka-data1
status: {}
