apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: kafkadeneme
  name: kafkadeneme
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafkadeneme
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/opt-default: "true"
        io.kompose.service: kafkadeneme
    spec:
      containers:
        - env:
            - name: MONGODB_C
              value: taha1216
            - name: MONGODB_DB
              value: kafka-deneme
            - name: PORT
              value: "8000"
          image: kafkadeneme
          name: kafkadeneme
          ports:
            - containerPort: 8000
          resources: {}
          volumeMounts:
            - mountPath: /deneme-site.py
              name: kafkadeneme-claim0
            - mountPath: /index.html
              name: kafkadeneme-claim1
      restartPolicy: Always
      volumes:
        - name: kafkadeneme-claim0
          persistentVolumeClaim:
            claimName: kafkadeneme-claim0
        - name: kafkadeneme-claim1
          persistentVolumeClaim:
            claimName: kafkadeneme-claim1
status: {}
