apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-topics
  name: kafka-topics
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-topics
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/opt-default: "true"
        io.kompose.service: kafka-topics
    spec:
      containers:
        - args:
            - bash
            - -c
            - echo creating topics && kafka-topics --bootstrap-server kafka-1:9092 --create --topic X --partitions 1 --replication-factor 3
          image: confluentinc/cp-kafka:5.5.0
          name: kafka-topics
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/kafka/data
              name: kafka-topic-data
            - mountPath: /etc/kafka/secrets
              name: kafka-topic-data
      restartPolicy: Always
      volumes:
        - name: kafka-topic-data
          persistentVolumeClaim:
            claimName: kafka-topic-data
        - name: kafka-topic-data
          persistentVolumeClaim:
            claimName: kafka-topic-data
status: {}
