apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/opt-default: "true"
        io.kompose.service: mongo
    spec:
      containers:
        - args:
            - mongod
            - --replSet
            - mongoSet
          image: mongo:latest
          name: mongo
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/configdb
              name: mongo-data1
            - mountPath: /data/db
              name: mongo-data1
      restartPolicy: Always
      volumes:
        - name: mongo-data1
          persistentVolumeClaim:
            claimName: mongo-data1
        - name: mongo-data1
          persistentVolumeClaim:
            claimName: mongo-data1
status: {}
