apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-init
  name: mongo-init
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo-init
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/opt-default: "true"
        io.kompose.service: mongo-init
    spec:
      containers:
        - args:
            - mongosh
            - --host
            - mongo
            - --eval
            - rs.initiate({_id:"mongoSet",members:[{_id:0,host:"mongo:27017"},{_id:1,host:"m1:27017"},{_id:2,host:"m2:27017"}]});
          image: mongo:latest
          name: mongo-init
          resources: {}
          volumeMounts:
            - mountPath: /data/configdb
              name: mongo-init-data
            - mountPath: /data/db
              name: mongo-init-data
      restartPolicy: Always
      volumes:
        - name: mongo-init-data
          persistentVolumeClaim:
            claimName: mongo-init-data
        - name: mongo-init-data
          persistentVolumeClaim:
            claimName: mongo-init-data
status: {}
