apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: producer
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: producer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/opt-default: "true"
        io.kompose.service: producer
    spec:
      containers:
        - env:
            - name: KAFKA_BROKERCONNECT
              value: kafka-1:9092
            - name: MONGODB_C
              value: taha1216
            - name: MONGODB_DB
              value: kafka-deneme
            - name: TOPIC
              value: X
          image: producer
          name: producer
          resources: {}
          volumeMounts:
            - mountPath: /kafkarun.py
              name: producer-claim0
      restartPolicy: Always
      volumes:
        - name: producer-claim0
          persistentVolumeClaim:
            claimName: producer-claim0
status: {}
